### ISSUE TITLE
Team Text content is incomplete

### ISSUE THREAD

**Issue by dirkroorda** [knaw-huc/di-website#13]

**Comment by kintopp** [comment]
I used deepl.com to make a first, draft auto-translation. This still need to be checked. @hennie Could you please take a look? Various gaps in the content also need to filled.

**Comment by kintopp** [comment]
https://beta-di.diginfra.net/beta/tekstanalyse-nl.html
https://beta-di.diginfra.net/beta/text-analysis-en.html
