### ISSUE TITLE
Improve contact options in footer

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#23]
Mario suggests adding a contact form, in particular in the footer, which now just lists a telephone number.

**Comment by kintopp** [comment]
@wmvanderveen I can't remember, did we decide in the end to link the contact page link in the footer to the Dutch or the English contact page?

**Comment by wmvanderveen** [comment]
To the English contact page.

**Comment by kintopp** [comment]
We don't have a link to the Humanities Cluster in the footer. My suggestion:

Powered by:
KNAW Humanities Cluster
- Huygens Instituut
- IISG
- Meertens Instituut

**Comment by MennoRasch** [comment]
prima suggestie, laten we dat doen.

**Comment by wmvanderveen** [comment]
Prima
