### ISSUE TITLE
Replace all DI Infrastructure links on the HuC website

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#34]

**Comment by wmvanderveen** [comment]
Alle links in de lopende tekst verwijzen nu naar di.huc.knaw.nl.

**Comment by kintopp** [comment]
Also in the menus?

**Comment by kintopp** [comment]
Several menu items referencing DI still point to content inside huc.knaw.nl and not to di.huc.knaw.nl.

**Comment by wmvanderveen** [comment]
Links zowel in lopende tekst als in menu's aangepast.
