### ISSUE TITLE
Add a privacy notice?

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#35]
Do we need a GPDR privacy notice? I imagine we do, and since this is a new website, and we are the DI department, it's perhaps a little more awkward for us if we don't have one.

**Comment by MennoRasch** [comment]
geen idee of dit nodig is. deze website vraagt niet om privacy gevoelige informatie, toch? En cookies melding, of gebruiken we geen cookies (zou mooi zijn!).

**Comment by kintopp** [comment]
It looks like we have one tracker on the site from hotjar.com

**Comment by wmvanderveen** [comment]
The GDPR notice has to be a pop-up when you visit the page. That is something that has to be added by Bas. For now we can link in the footer to the KNAW: https://www.knaw.nl/privacy. Also to be added by Bas. :-)

**Comment by kintopp** [comment]
If no user identifying information is collected by us, and the site does not even set a cookie, do we still need a GDPR notice? What would we be allowing a visitor to 'opt out' of?

**Comment by MennoRasch** [comment]
Misschien verzamelen we wel ip adressen?

**Comment by kintopp** [comment]
Yes, that's possible, with the web server itself. Also, I suppose that when we add Matomo, further data collection is inevitable.
