### ISSUE TITLE
Find image for interview with Menno feature article

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#36]

**Comment by MennoRasch** [comment]
lastig. Ik kom nog niet verder dan iets van deze 3:
https://media-exp1.licdn.com/dms/image/C4D1BAQHkARoaMMupXQ/company-background_10000/0/1602660382902?e=1667577600&v=beta&t=v5eyhZUx4_WMuPg2lblZOJF4dE3E_-DIuB_oGaw6t-g https://upload.wikimedia.org/wikipedia/commons/1/18/Hoofdbureau-van-Politie-Amsterdam.jpg of 
https://assets.amsterdam.nl/publish/pages/914888/010094003898.jpg

**Comment by kintopp** [comment]
There is another solution: if Bas removes the space for the image, the text can take up the full width of the panel. It may even look better than what we have now: two identical layout underneath each other.

**Comment by MennoRasch** [comment]
ook een goede suggestie. Als we maar ook de mogelijkheid hebben om wel een plaatje neer te zetten, daardoor ziet de website er wel beter uit.

**Comment by Doppen** [comment]
Ik kan mijn camera dinsdag meenemen naar het Spinhuis voor een foto van Menno op zijn werkplek? Ik weet niet of Menno er dinsdag is?

**Comment by MennoRasch** [comment]
ik heb wel een goede foto, maar had wat schroom om die direct bij de lancering op de homepage te zetten....

**Comment by MennoRasch** [comment]
misschien moeten we dan toch maar gewoon mijn foto gebruiken? 
https://huc.knaw.nl/wp-content/uploads/Menno_Rasch.jpg
