### ISSUE TITLE
General review, clean-up and translations of Expertise texts

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#37]

**Comment by kintopp** [comment]
@MennoRasch I think the Concern Infrastructure text needs to be re-written at some point. It's currently both too generic and too short, and is also missing sub-sections on related projects, software, and publications.

**Comment by kintopp** [comment]
Completed. Several of the expertise texts could also use of a screenshot of a tool, project etc.

**Comment by MennoRasch** [comment]
ja, die tekst kunnen we nog wel een keer verbeteren, je hebt gelijk. Ik weet niet of er veel relevante publicaties zijn, maar natuurlijk wel goede projecten en software.

**Comment by kintopp** [comment]
Some people in Mario's group do have publications (see https://beta.huc.knaw.nl/infrastructure/concern-infrastructure/). Probably, there are more, if one includes presentations as well (as one should).
