### ISSUE TITLE
Final review and revision of Activities and About pages

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#39]

**Comment by MennoRasch** [comment]
ik kan hier niet meer neutraal door heen lezen :) Ik heb nog een poging gedaan, maar ik denk dat het goed is zo. het is immers ook bekeken door een heel aantal anderen. We wachten ook even af of er nog opmerkingen op komen, Maar ik sluit m af!

**Comment by kintopp** [comment]
I found a few minor translation and formatting issues which I'll fix this morning.
