### ISSUE TITLE
Safari menu/institute logos interaction bug

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#48]
When running the mouse down the menus in Safari v16.1 (OSX 12.6.1), it's possible to reproducibly trigger the institute logos jumping to the top of the menu div.

https://user-images.githubusercontent.com/963588/199069720-83e754c9-cb15-40a3-aa3c-cdba84af7fd8.mov

This doesn't happen in current FireFox or Chrome on the Mac.

**Comment by Doppen** [comment]
Story of my life in 17 seconds  :(

**Comment by kintopp** [comment]
My guess: If you can prevent the scroll bar from appearing in the navigation div when the menus get expanded, then the scroll bar won't take up any horizontal space, and then the icons won't be pushed up to the top.

**Comment by kintopp** [comment]
Fixed (by Apple) in current version of Safari (16.3).
