### ISSUE TITLE
Outdated DI page on huc.knaw.nl is top result for Google search

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/di-website#53]
Search in google for "di knaw". And the trouble is, not only does this page [still exist](https://huc.knaw.nl/di/), so does the associated sub-menu and all of its linked sub-pages e.g. for text, geo, images etc.

**Comment by wmvanderveen** [comment]
Ik heb alle relevante pagina's nu op Draft gezet. Hopelijk heeft dat snel effect. Zo niet, dan verwijder ik de pagina's.

**Comment by kintopp** [comment]
That should work but I've also saved (exported) the whole HuC site, so it's ok to completely delete the old content as well.
