### ISSUE TITLE
Footer doesn't follow language + Spelling

### ISSUE THREAD

**Issue by stefanklut** [knaw-huc/di-website#54]
The link to contact is always the English link. Also the Address field is currently wrong in both languages. 
Dutch: Adres, English: Address, Currenly on the site: Adress.

**Comment by kintopp** [comment]
Odd. It should be using the English version for both (as a compromise/simplification). Address is spelled correctly [here](https://github.com/knaw-huc/di-website/blob/main/content/template/huc_di/components/huc_footer.html) which is what I thought the footer was drawing on.
